
pacman::p_load(sf,
               tidyverse,
               dataRetrieval,
               terra,
               whitebox,
               tmap,
               tidygraph,
               igraph,
               sfnetworks,
               exactextractr,
               vegan,
               ggraph,
               foreach,
               glmnet,
               data.table)
